/** AUTO-GENERATED by scripts/build-runtime-payload.mjs — do not edit. */
export declare const BUNDLED_RUNTIME_VERSION: string;
export declare const BUNDLED_TFJS_VERSION: string;
export declare const BUNDLED_TFJS_JS: string;
export declare const BUNDLED_TFJS_WASM_JSON: string;
export declare const BUNDLED_MODEL_JSON: string;
export declare const BUNDLED_WEIGHTS_JSON: string;
export declare const BUNDLED_PIPELINE_WASM_B64: string;
export declare const BUNDLED_RUNTIME_JS: string;
